version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0  # You can change to 6.0, 7.0, etc.
    steps:
      - checkout

      - run:
          name: Restore Dependencies
          command: dotnet restore StudentForm.sln

      - run:
          name: Build the Solution
          command: dotnet build StudentForm.sln --configuration Release

      - run:
          name: Run Unit Tests
          command: dotnet test StudentForm.Tests/StudentForm.Tests.csproj --no-build --verbosity normal

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
